global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'mongodb'
    static_configs:
      - targets: ['mongo_exporter:9216', 'mongo_exporter_2:9216', 'mongo_exporter3:9216']
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187', 'postgres-exporter_2:9187']